---
title: 第 11 章. 手册页
prev: books/fdp-primer/weblate
next: books/fdp-primer/writing-style
description: 如何使用 FreeBSD 手册页
tags: ["manual pages", "introduction", "guide", "reference"]
showBookMenu: true
weight: 11
params:
  path: "/books/fdp-primer/manual-pages/"
---

[[manual-pages]]
= 手册页
:doctype: book
:toc: macro
:toclevels: 1
:icons: font
:sectnums:
:sectnumlevels: 6
:sectnumoffset: 11
:partnums:
:source-highlighter: rouge
:experimental:
:images-path: books/fdp-primer/

ifdef::env-beastie[]
ifdef::backend-html5[]
:imagesdir: ../../../../images/{images-path}
endif::[]
ifndef::book[]
include::shared/authors.adoc[]
include::shared/mirrors.adoc[]
include::shared/releases.adoc[]
include::shared/attributes/attributes-{{% lang %}}.adoc[]
include::shared/{{% lang %}}/teams.adoc[]
include::shared/{{% lang %}}/mailing-lists.adoc[]
include::shared/{{% lang %}}/urls.adoc[]
toc::[]
endif::[]
ifdef::backend-pdf,backend-epub3[]
include::../../../../../shared/asciidoctor.adoc[]
endif::[]
endif::[]

ifndef::env-beastie[]
toc::[]
include::../../../../../shared/asciidoctor.adoc[]
endif::[]

[[manual-pages-introduction]]
== 引言

_手册页_，通常简称为 _man pages_，最初被设想为随时可用的提醒，用于命令语法、设备驱动程序详细信息或配置文件格式。
它们已成为用户、系统管理员和程序员在命令行上非常有价值的快速参考。

尽管旨在作为参考材料而非教程，但手册页的“示例”部分通常提供详细的用例。

手册页通常由 man:man[1] 命令以交互方式显示。
当用户键入 `man ls` 时，会搜索与 `ls` 匹配的手册页。
将显示第一个匹配的结果。

[[manual-pages-sections]]
== 章节

手册页分为 _章节_。
每个章节包含特定类别文档的手册页：

[.informaltable]
[cols="1,8", options="header"]
|===
| 章节号
| 类别


|1
|通用命令

|2
|系统调用

|3
|库函数

|4
|内核接口

|5
|文件格式

|6
|游戏

|7
|杂项

|8
|系统管理员

|9
|内核开发人员
|===

[[manual-pages-markup]]
== 标记

手册页使用了各种标记形式和渲染程序。
FreeBSD 使用过 man:groff[7] 和较新的 man:mandoc[1]。
大多数现有的 FreeBSD 手册页以及所有新的手册页都使用 man:mdoc[7] 形式的标记。
这是一种简单的基于行的标记，具有相当强的表现力。
它主要是语义化的：文本的各个部分根据其内容进行标记，而不是根据其渲染时的外观。
有一些基于外观的标记，通常最好避免使用。

手册页源文件通常被解释并以交互方式显示在屏幕上。
源文件可以是普通文本文件，也可以使用 man:gzip[1] 压缩以节省空间。

手册页也可以渲染为其他格式，包括用于打印或生成 PDF 的 PostScript。
请参阅 man:man[1]。

[[manual-pages-markup-sections]]
=== 手册页章节

手册页由几个标准章节组成。
每个章节都有一个大写标题，特定类型手册页的章节按特定顺序出现。
对于第 1 类通用命令手册页，章节如下：

[.informaltable]
[cols="2,4", options="header"]
|===
| 章节名称
| 描述


|NAME
|命令的名称

|SYNOPSIS
|选项和参数的格式

|DESCRIPTION
|目的和用法描述

|ENVIRONMENT
|影响操作的环境设置

|EXIT STATUS
|退出时返回的错误代码

|EXAMPLES
|用法示例

|COMPATIBILITY
|与其他实现的兼容性

|SEE ALSO
|相关手册页的交叉引用

|STANDARDS
|与 POSIX 等标准的兼容性

|HISTORY
|实现历史

|BUGS
|已知错误

|AUTHORS
|创建命令或编写手册页的人员。
|===

有些章节是可选的，特定类型手册页的章节组合各不相同。
本章后面将展示最常见类型的示例。

[[manual-pages-markup-macros]]
=== 宏

man:mdoc[7] 标记基于 _宏_。
以点开头的行包含宏命令，每个命令长两到三个字母。
例如，考虑 man:ls[1] 手册页的这一部分：

[.programlisting]
....
.Dd December 1, 2015  <.>
.Dt LS 1
.Sh NAME  <.>
.Nm ls
.Nd list directory contents
.Sh SYNOPSIS  <.>
.Nm  <.>
.Op Fl -libxo  <.>
.Op Fl ABCFGHILPRSTUWZabcdfghiklmnopqrstuwxy1,  <.>
.Op Fl D Ar format  <.>
.Op Ar  <.>
.Sh DESCRIPTION  <.>
For each operand that names a
.Ar file
of a type other than
directory,
.Nm
displays its name as well as any requested,
associated information.
For each operand that names a
.Ar file
of type directory,
.Nm
displays the names of files contained
within that directory, as well as any requested, associated
information.
....

<.> 定义了 _文档日期_ 和 _文档标题_。
<.> 定义了 NAME 章节的 _章节标题_。
然后定义了命令的 _名称_ 和一行的 _名称描述_。
<.> SYNOPSIS 章节开始。
本节描述了接受的命令行选项和参数。
<.> _名称_ (`.Nm`) 已经定义，在这里重复它只是在文本中显示已定义的值。
<.> 显示了一个名为 `-libxo` 的 _可选_ _标志_。
`Fl` 宏在标志的开头添加一个破折号，因此这在手册页中显示为 `--libxo`。
<.> 显示了一长串可选的单字符标志。
<.> 定义了一个可选的 `-D` 标志。
如果给出了 `-D` 标志，则必须后跟一个 _参数_。
该参数是一个 _格式_，一个告诉 man:ls[1] 显示什么以及如何显示的字符串。
有关格式字符串的详细信息在手册页的后面给出。
<.> 定义了最后一个可选参数。
由于没有为参数指定名称，因此使用默认的 `file ...`。
<.> 定义了 DESCRIPTION 章节的 _章节标题_。

当使用命令 `man ls` 渲染时，屏幕上显示的结果如下所示：

[.programlisting]
....
LS(1)                   FreeBSD General Commands Manual                  LS(1)

NAME
     ls - list directory contents

SYNOPSIS
     ls [--libxo] [-ABCFGHILPRSTUWZabcdfghiklmnopqrstuwxy1,] [-D format]
        [file ...]

DESCRIPTION
     For each operand that names a file of a type other than directory, ls
     displays its name as well as any requested, associated information.  For
     each operand that names a file of type directory, ls displays the names
     of files contained within that directory, as well as any requested,
     associated information.
....

可选值显示在方括号内。

[[manual-pages-markup-guidelines]]
=== 标记指南

man:mdoc[7] 标记语言不是很严格。
为了清晰和一致，FreeBSD 文档项目添加了一些额外的样式指南：

只有宏的第一个字母大写::
始终对宏的第一个字母使用大写，其余字母使用小写。

在新行上开始新句子::
在新行上开始一个新句子，不要在现有句子的同一行上开始它。

对非平凡的更改更新 `.Dd`::
_文档日期_ 告知读者手册页的最后更新时间。
每当对手册页进行非平凡的更改时，更新它很重要。
可以不更新 `.Dd` 就进行拼写或标点修复等不影响用法的琐碎更改。

提供示例::
尽可能向读者展示示例。
即使是琐碎的示例也很有价值，因为对作者来说琐碎的事情对读者来说不一定琐碎。
三个示例是一个好目标。
一个琐碎的示例展示了最低要求，一个严肃的示例展示了实际用法，一个深入的示例演示了不寻常或不明显的功能。

包含 BSD 许可证::
在新手册页上包含 BSD 许可证。
首选的许可证可从 extref:{committers-guide}[提交者指南] 获得。

[[manual-pages-markup-tricks]]
=== 标记技巧

在带有宏的行上的标点符号前添加一个空格。示例：

[.programlisting]
....
.Sh SEE ALSO
.Xr geom 4 ,
.Xr boot0cfg 8 ,
.Xr geom 8 ,
.Xr gptboot 8
....

请注意，`.Xr` 行末尾的逗号是如何放在一个空格之后的。
`.Xr` 宏期望后面有两个参数，一个外部手册页的名称和一个章节号。
空格将标点符号与章节号分开。
没有空格，外部链接将错误地指向章节 `4,` 或 `8,`。

[[manual-pages-markup-important-macros]]
=== 重要宏

这里将展示一些非常常见的宏。
有关更多用法示例，请参阅 man:mdoc[7]、man:groff_mdoc[7]，或在 [.filename]#/usr/share/man/man*# 目录中搜索实际用法。
例如，要搜索 `.Bd` _开始显示_ 宏的示例：

[source,shell]
....
% find /usr/share/man/man* | xargs zgrep '.Bd'
....

[[manual-pages-markup-important-macros-organizational]]
==== 组织宏

一些宏用于定义手册页的逻辑块。

[.informaltable]
[cols="1,8", options="header"]
|===
| 组织宏
| 用途


|`.Sh`
|章节标题。
后跟章节名称，传统上全部大写。
可以将其视为章节标题。

|`.Ss`
|小节标题。
后跟小节名称。
用于将 `.Sh` 章节划分为小节。

|`.Bl`
|开始列表。开始一个项目列表。

|`.El`
|结束列表。

|`.Bd`
|开始显示。
开始一个特殊的文本区域，如缩进区域。

|`.Ed`
|结束显示。
|===

[[manual-pages-markup-important-macros-inline]]
==== 内联宏

许多宏用于标记内联文本。

[.informaltable]
[cols="1,8", options="header"]
|===
| 内联宏
| 用途


|`.Nm`
|名称。
第一次使用时以名称作为参数调用，然后不带参数使用以显示已定义的名称。

|`.Pa`
|文件路径。
用于标记文件名和目录路径。
|===

[[manual-pages-sample-structures]]
== 示例手册页结构

本节展示了几种常见类别手册页的最低要求内容。

[[manual-pages-sample-structures-section-1-8]]
=== 第 1 或 8 节命令

第 1 或 8 节命令的首选基本结构：

[.programlisting]
....
.Dd August 25, 2017
.Dt EXAMPLECMD 8
.Os
.Sh NAME
.Nm examplecmd
.Nd "command to demonstrate section 1 and 8 man pages"
.Sh SYNOPSIS
.Nm
.Op Fl v
.Sh DESCRIPTION
The
.Nm
utility does nothing except demonstrate a trivial but complete
manual page for a section 1 or 8 command.
.Sh SEE ALSO
.Xr exampleconf 5
.Sh AUTHORS
.An Firstname Lastname Aq Mt flastname@example.com
....

[[manual-pages-sample-structures-section-4]]
=== 第 4 节设备驱动程序

第 4 节设备驱动程序的首选基本结构：

[.programlisting]
....
.Dd August 25, 2017
.Dt EXAMPLEDRIVER 4
.Os
.Sh NAME
.Nm exampledriver
.Nd "driver to demonstrate section 4 man pages"
.Sh SYNOPSIS
To compile this driver into the kernel, add this line to the
kernel configuration file:
.Bd -ragged -offset indent
.Cd "device exampledriver"
.Ed
.Pp
To load the driver as a module at boot, add this line to
.Xr loader.conf 5 :
.Bd -literal -offset indent
exampledriver_load="YES"
.Ed
.Sh DESCRIPTION
The
.Nm
driver provides an opportunity to show a skeleton or template
file for section 4 manual pages.
.Sh HARDWARE
The
.Nm
driver supports these cards from the aptly-named Nonexistent
Technologies:
.Pp
.Bl -bullet -compact
.It
NT X149.2 (single and dual port)
.It
NT X149.8 (single port)
.El
.Sh DIAGNOSTICS
.Bl -diag
.It "flashing green light"
Something bad happened.
.It "flashing red light"
Something really bad happened.
.It "solid black light"
Power cord is unplugged.
.El
.Sh SEE ALSO
.Xr example 8
.Sh HISTORY
The
.Nm
device driver first appeared in
.Fx 49.2 .
.Sh AUTHORS
.An Firstname Lastname Aq Mt flastname@example.com
....

[[manual-pages-sample-structures-section-5]]
=== 第 5 节配置文件

第 5 节配置文件的首选基本结构：

[.programlisting]
....
.Dd August 25, 2017
.Dt EXAMPLECONF 5
.Os
.Sh NAME
.Nm example.conf
.Nd "config file to demonstrate section 5 man pages"
.Sh DESCRIPTION
.Nm
is an example configuration file.
.Sh SEE ALSO
.Xr example 8
.Sh AUTHORS
.An Firstname Lastname Aq Mt flastname@example.com
....

[[manual-pages-testing]]
== 测试

测试新的手册页可能具有挑战性。
幸运的是，有一些工具可以帮助完成这项任务。
其中一些，如 man:man[1]，不会在当前目录中查找。
如果新的手册页在当前目录中，最好在文件名前加上 `./`。
也可以使用绝对路径。

使用 man:mandoc[1] 的 linter 检查解析错误：

[source,shell]
....
% mandoc -T lint ./mynewmanpage.8
....

使用 package:textproc/igor[] 校对 手册页：

[source,shell]
....
% igor ./mynewmanpage.8
....

另一个有用的工具是 package:textproc/vale[]。
它不支持 man:mdoc[7] 语法，但可以从标准输入读取渲染的手册页：

[source,shell]
....
% man ls | vale
....

package:textproc/vale[] 是高度可配置的。
建议阅读其文档。

使用 man:man[1] 检查更改的最终结果：

[source,shell]
....
% man ./mynewmanpage.8
....

您可以使用 man:col[1] 过滤 man:man[1] 的输出，并在将结果加载到您喜欢的编辑器中进行拼写检查之前去掉退格字符：

[source,shell]
....
% man ./mynewmanpage.8 | col -b | vim -R -
....

鼓励使用功能齐全的词典进行拼写检查，
可以通过分别使用 package:textproc/hunspell[] 或 package:textproc/aspell[] 与 package:textproc/en-hunspell[] 或 package:textproc/en-aspell[] 相结合来实现。
例如：

[source,shell]
....
% aspell check --lang=en --mode=nroff ./mynewmanpage.8
....

[[manual-pages-examples-as-templates]]
== 用作模板的示例手册页

一些手册页适合作为深入的示例。

[.informaltable]
[cols="1,4", options="header"]
|===
| 手册页
| 源位置路径


|man:cp[1]
|[.filename]#/usr/src/bin/cp/cp.1#

|man:vt[4]
|[.filename]#/usr/src/share/man/man4/vt.4#

|man:crontab[5]
|[.filename]#/usr/src/usr.sbin/cron/crontab/crontab.5#

|man:gpart[8]
|[.filename]#/usr/src/sbin/geom/class/part/gpart.8#
|===

[[manual-pages-resources]]
== 资源

手册页编写者资源：

* man:man[1]
* man:mandoc[1]
* man:style.mdoc[5]
* man:groff_mdoc[7]
* http://manpages.bsd.lv/mdoc.html[Practical UNIX Manuals: mdoc]
* http://manpages.bsd.lv/history.html[History of UNIX Manpages]
