---
title: 第 11 章. 手冊頁面
prev: books/fdp-primer/weblate
next: books/fdp-primer/writing-style
description: 如何使用 FreeBSD 手冊頁面
tags: ["manual pages", "introduction", "guide", "reference"]
showBookMenu: true
weight: 11
params:
  path: "/books/fdp-primer/manual-pages/"
---

[[manual-pages]]
= 手冊頁面
:doctype: book
:toc: macro
:toclevels: 1
:icons: font
:sectnums:
:sectnumlevels: 6
:sectnumoffset: 11
:partnums:
:source-highlighter: rouge
:experimental:
:images-path: books/fdp-primer/

ifdef::env-beastie[]
ifdef::backend-html5[]
:imagesdir: ../../../../images/{images-path}
endif::[]
ifndef::book[]
include::shared/authors.adoc[]
include::shared/mirrors.adoc[]
include::shared/releases.adoc[]
include::shared/attributes/attributes-{{% lang %}}.adoc[]
include::shared/{{% lang %}}/teams.adoc[]
include::shared/{{% lang %}}/mailing-lists.adoc[]
include::shared/{{% lang %}}/urls.adoc[]
toc::[]
endif::[]
ifdef::backend-pdf,backend-epub3[]
include::../../../../../shared/asciidoctor.adoc[]
endif::[]
endif::[]

ifndef::env-beastie[]
toc::[]
include::../../../../../shared/asciidoctor.adoc[]
endif::[]

[[manual-pages-introduction]]
== 簡介

_手冊頁面_，通常簡稱為 _man pages_，最初被設想為方便取得的指令語法、裝置驅動程式詳細資訊或設定檔格式的提醒。
它們已成為使用者、系統管理員和程式設計師在命令列上非常有價值的快速參考。

雖然手冊頁面旨在作為參考資料而非教學，但其 EXAMPLES 部分通常提供詳細的使用案例。

手冊頁面通常由 man:man[1] 指令以互動方式顯示。
當使用者輸入 `man ls` 時，會搜尋符合 `ls` 的手冊頁面。
第一個符合的結果會被顯示。

[[manual-pages-sections]]
== 區段

手冊頁面分組為 _區段_。
每個區段包含特定類別文件的手冊頁面：

[.informaltable]
[cols="1,8", options="header"]
|===
| 區段編號
| 類別


|1
|一般指令

|2
|系統呼叫

|3
|函式庫函式

|4
|核心介面

|5
|檔案格式

|6
|遊戲

|7
|雜項

|8
|系統管理員

|9
|核心開發人員
|===

[[manual-pages-markup]]
== 標記

手冊頁面曾使用過各種標記形式和呈現程式。
FreeBSD 使用過 man:groff[7] 和較新的 man:mandoc[1]。
大多數現有的 FreeBSD 手冊頁面以及所有新的手冊頁面都使用 man:mdoc[7] 形式的標記。
這是一種簡單的以行為基礎的標記，具有相當的表達能力。
它主要是語意化的：文本的各部分根據其是什麼來標記，而不是根據其在呈現時應如何顯示。
有一些基於外觀的標記，通常最好避免使用。

手冊頁面原始碼通常會被互動式地解譯並顯示在螢幕上。
原始檔可以是普通文字檔，也可以使用 man:gzip[1] 壓縮以節省空間。

手冊頁面也可以呈現為其他格式，包括用於列印的 PostScript 或 PDF 產生。
請參閱 man:man[1]。

[[manual-pages-markup-sections]]
=== 手冊頁面區段

手冊頁面由數個標準區段組成。
每個區段都有一個大寫的標題，特定類型手冊頁面的區段會以特定順序出現。
對於第 1 類一般指令手冊頁面，區段如下：

[.informaltable]
[cols="2,4", options="header"]
|===
| 區段名稱
| 說明


|NAME
|指令名稱

|SYNOPSIS
|選項和引數的格式

|DESCRIPTION
|目的和用法說明

|ENVIRONMENT
|影響操作的環境設定

|EXIT STATUS
|結束時傳回的錯誤碼

|EXAMPLES
|用法範例

|COMPATIBILITY
|與其他實作的相容性

|SEE ALSO
|相關手冊頁面的交互參考

|STANDARDS
|與 POSIX 等標準的相容性

|HISTORY
|實作歷史

|BUGS
|已知錯誤

|AUTHORS
|建立指令或撰寫手冊頁面的人員。
|===

某些區段是選用的，特定類型手冊頁面的區段組合會有所不同。
本章稍後將顯示最常見類型的範例。

[[manual-pages-markup-macros]]
=== 巨集

man:mdoc[7] 標記基於 _巨集_。
以點號開頭的行包含巨集指令，每個指令長度為二或三個字母。
例如，請看 man:ls[1] 手冊頁面的這一部分：

[.programlisting]
....
.Dd December 1, 2015  <.>
.Dt LS 1
.Sh NAME  <.>
.Nm ls
.Nd list directory contents
.Sh SYNOPSIS  <.>
.Nm  <.>
.Op Fl -libxo  <.>
.Op Fl ABCFGHILPRSTUWZabcdfghiklmnopqrstuwxy1,  <.>
.Op Fl D Ar format  <.>
.Op Ar  <.>
.Sh DESCRIPTION  <.>
For each operand that names a
.Ar file
of a type other than
directory,
.Nm
displays its name as well as any requested,
associated information.
For each operand that names a
.Ar file
of type directory,
.Nm
displays the names of files contained
within that directory, as well as any requested, associated
information.
....

<.> 定義了 _文件日期_ 和 _文件標題_。
<.> 定義了 NAME 區段的 _區段標頭_。
然後定義了指令的 _名稱_ 和一行 _名稱說明_。
<.> SYNOPSIS 區段開始。
此區段說明接受的命令列選項和引數。
<.> _名稱_ (`.Nm`) 已定義，在此處重複它只會顯示文字中已定義的值。
<.> 顯示了一個名為 `-libxo` 的 _選用_ _旗標_。
`Fl` 巨集會在旗標開頭加上一個破折號，因此這在手冊頁面中顯示為 `--libxo`。
<.> 顯示了一長串選用的單一字元旗標。
<.> 定義了一個選用的 `-D` 旗標。
如果給定 `-D` 旗標，則必須跟著一個 _引數_。
引數是一個 _格式_，一個告訴 man:ls[1] 要顯示什麼以及如何顯示的字串。
格式字串的詳細資訊在手冊頁面稍後提供。
<.> 定義了最後一個選用引數。
由於未指定引數的名稱，因此使用預設的 `file ...`。
<.> 定義了 DESCRIPTION 區段的 _區段標頭_。

使用指令 `man ls` 呈現時，螢幕上顯示的結果如下：

[.programlisting]
....
LS(1)                   FreeBSD General Commands Manual                  LS(1)

NAME
     ls - list directory contents

SYNOPSIS
     ls [--libxo] [-ABCFGHILPRSTUWZabcdfghiklmnopqrstuwxy1,] [-D format]
        [file ...]

DESCRIPTION
     For each operand that names a file of a type other than directory, ls
     displays its name as well as any requested, associated information.  For
     each operand that names a file of type directory, ls displays the names
     of files contained within that directory, as well as any requested,
     associated information.
....

選用值會顯示在方括號內。

[[manual-pages-markup-guidelines]]
=== 標記指南

man:mdoc[7] 標記語言不是很嚴格。
為了清晰和一致，FreeBSD 文件專案新增了一些額外的樣式指南：

只有巨集的第一個字母大寫：：
巨集的第一個字母一律使用大寫，其餘字母使用小寫。

新句子另起一行：：
新句子另起一行，不要與現有句子在同一行開始。

對手冊頁面進行非小幅變更時更新 `.Dd`：：
_文件日期_ 會告知讀者手冊頁面最後一次更新的時間。
對手冊頁面進行非小幅變更時更新很重要。
拼字或標點符號修正等不影響用法的小幅變更可以不更新 `.Dd`。

提供範例：：
盡可能向讀者展示範例。
即使是簡單的範例也很有價值，因為對作者來說簡單的事情對讀者來說不一定簡單。
三個範例是一個很好的目標。
一個簡單的範例展示了最低要求，一個認真的範例展示了實際用法，一個深入的範例展示了不尋常或不明顯的功能。

包含 BSD 授權：：
在新手冊頁面上包含 BSD 授權。
偏好的授權可從 extref:{committers-guide}[Committer's Guide] 取得。

[[manual-pages-markup-tricks]]
=== 標記技巧

在帶有巨集的行上的標點符號前加上一個空格。範例：

[.programlisting]
....
.Sh SEE ALSO
.Xr geom 4 ,
.Xr boot0cfg 8 ,
.Xr geom 8 ,
.Xr gptboot 8
....

請注意，`.Xr` 行結尾的逗號是如何放在空格後面的。
`.Xr` 巨集預期後面跟著兩個參數，一個外部手冊頁面的名稱和一個區段編號。
空格將標點符號與區段編號分開。
如果沒有空格，外部連結會錯誤地指向區段 `4,` 或 `8,`。

[[manual-pages-markup-important-macros]]
=== 重要巨集

這裡將展示一些非常常見的巨集。
有關更多用法範例，請參閱 man:mdoc[7]、man:groff_mdoc[7]，或在 [.filename]#/usr/share/man/man*# 目錄中搜尋實際用法。
例如，若要搜尋 `.Bd` _Begin display_ 巨集的範例：

[source,shell]
....
% find /usr/share/man/man* | xargs zgrep '.Bd'
....

[[manual-pages-markup-important-macros-organizational]]
==== 組織巨集

某些巨集用於定義手冊頁面的邏輯區塊。

[.informaltable]
[cols="1,8", options="header"]
|===
| 組織巨集
| 用途


|`.Sh`
|區段標頭。
後面跟著區段的名稱，傳統上全部大寫。
可以把它們想成是章節標題。

|`.Ss`
|子區段標頭。
後面跟著子區段的名稱。
用於將 `.Sh` 區段劃分為子區段。

|`.Bl`
|開始列表。開始一個項目列表。

|`.El`
|結束列表。

|`.Bd`
|開始顯示。
開始一個特殊的文字區域，例如縮排區域。

|`.Ed`
|結束顯示。
|===

[[manual-pages-markup-important-macros-inline]]
==== 行內巨集

許多巨集用於標記行內文字。

[.informaltable]
[cols="1,8", options="header"]
|===
| 行內巨集
| 用途


|`.Nm`
|名稱。
第一次使用時以名稱作為參數呼叫，之後不帶參數使用以顯示已定義的名稱。

|`.Pa`
|檔案路徑。
用於標記檔名和目錄路徑。
|===

[[manual-pages-sample-structures]]
== 手冊頁面結構範例

本節顯示了幾種常見手冊頁面類別的最低要求內容。

[[manual-pages-sample-structures-section-1-8]]
=== 第 1 或 8 區段指令

第 1 或 8 區段指令的偏好基本結構：

[.programlisting]
....
.Dd August 25, 2017
.Dt EXAMPLECMD 8
.Os
.Sh NAME
.Nm examplecmd
.Nd "command to demonstrate section 1 and 8 man pages"
.Sh SYNOPSIS
.Nm
.Op Fl v
.Sh DESCRIPTION
The
.Nm
utility does nothing except demonstrate a trivial but complete
manual page for a section 1 or 8 command.
.Sh SEE ALSO
.Xr exampleconf 5
.Sh AUTHORS
.An Firstname Lastname Aq Mt flastname@example.com
....

[[manual-pages-sample-structures-section-4]]
=== 第 4 區段裝置驅動程式

第 4 區段裝置驅動程式的偏好基本結構：

[.programlisting]
....
.Dd August 25, 2017
.Dt EXAMPLEDRIVER 4
.Os
.Sh NAME
.Nm exampledriver
.Nd "driver to demonstrate section 4 man pages"
.Sh SYNOPSIS
To compile this driver into the kernel, add this line to the
kernel configuration file:
.Bd -ragged -offset indent
.Cd "device exampledriver"
.Ed
.Pp
To load the driver as a module at boot, add this line to
.Xr loader.conf 5 :
.Bd -literal -offset indent
exampledriver_load="YES"
.Ed
.Sh DESCRIPTION
The
.Nm
driver provides an opportunity to show a skeleton or template
file for section 4 manual pages.
.Sh HARDWARE
The
.Nm
driver supports these cards from the aptly-named Nonexistent
Technologies:
.Pp
.Bl -bullet -compact
.It
NT X149.2 (single and dual port)
.It
NT X149.8 (single port)
.El
.Sh DIAGNOSTICS
.Bl -diag
.It "flashing green light"
Something bad happened.
.It "flashing red light"
Something really bad happened.
.It "solid black light"
Power cord is unplugged.
.El
.Sh SEE ALSO
.Xr example 8
.Sh HISTORY
The
.Nm
device driver first appeared in
.Fx 49.2 .
.Sh AUTHORS
.An Firstname Lastname Aq Mt flastname@example.com
....

[[manual-pages-sample-structures-section-5]]
=== 第 5 區段設定檔

第 5 區段設定檔的偏好基本結構：

[.programlisting]
....
.Dd August 25, 2017
.Dt EXAMPLECONF 5
.Os
.Sh NAME
.Nm example.conf
.Nd "config file to demonstrate section 5 man pages"
.Sh DESCRIPTION
.Nm
is an example configuration file.
.Sh SEE ALSO
.Xr example 8
.Sh AUTHORS
.An Firstname Lastname Aq Mt flastname@example.com
....

[[manual-pages-testing]]
== 測試

測試新的手冊頁面可能具有挑戰性。
幸運的是，有一些工具可以協助這項工作。
其中一些工具，例如 man:man[1]，不會在目前目錄中尋找。
如果新的手冊頁面位於目前目錄中，建議在檔名前加上 `./`。
也可以使用絕對路徑。

使用 man:mandoc[1] 的 linter 檢查剖析錯誤：

[source,shell]
....
% mandoc -T lint ./mynewmanpage.8
....

使用 package:textproc/igor[] 校對手冊頁面：

[source,shell]
....
% igor ./mynewmanpage.8
....

另一個有用的工具是 package:textproc/vale[]。
它不支援 man:mdoc[7] 語法，但可以從標準輸入讀取呈現的手冊頁面：

[source,shell]
....
% man ls | vale
....

package:textproc/vale[] 是高度可設定的。
建議閱讀其文件。

使用 man:man[1] 檢查變更的最終結果：

[source,shell]
....
% man ./mynewmanpage.8
....

您可以使用 man:col[1] 過濾 man:man[1] 的輸出，並在將結果載入您喜歡的編輯器進行拼字檢查之前去除退格字元：

[source,shell]
....
% man ./mynewmanpage.8 | col -b | vim -R -
....

鼓勵使用功能齊全的字典進行拼字檢查，
可以透過使用 package:textproc/hunspell[] 或 package:textproc/aspell[] 分別與 package:textproc/en-hunspell[] 或 package:textproc/en-aspell[] 結合來完成。
例如：

[source,shell]
....
% aspell check --lang=en --mode=nroff ./mynewmanpage.8
....

[[manual-pages-examples-as-templates]]
== 可用作範本的範例手冊頁面

某些手冊頁面適合作為深入的範例。

[.informaltable]
[cols="1,4", options="header"]
|===
| 手冊頁面
| 原始碼位置路徑


|man:cp[1]
|[.filename]#/usr/src/bin/cp/cp.1#

|man:vt[4]
|[.filename]#/usr/src/share/man/man4/vt.4#

|man:crontab[5]
|[.filename]#/usr/src/usr.sbin/cron/crontab/crontab.5#

|man:gpart[8]
|[.filename]#/usr/src/sbin/geom/class/part/gpart.8#
|===

[[manual-pages-resources]]
== 資源

手冊頁面作者的資源：

* man:man[1]
* man:mandoc[1]
* man:style.mdoc[5]
* man:groff_mdoc[7]
* http://manpages.bsd.lv/mdoc.html[Practical UNIX Manuals: mdoc]
* http://manpages.bsd.lv/history.html[History of UNIX Manpages]
