---
title: 附錄 A. 範例
prev: books/fdp-primer/see-also/
description: FreeBSD 文件計畫中使用的文章和書籍範例
tags: ["examples", "tutorial", "AsciiDoctor", "Book", "Article"]
showBookMenu: true
weight: 16
params:
  path: "/books/fdp-primer/examples/"
---

[appendix]
[[examples]]
= 範例
:doctype: book
:toc: macro
:toclevels: 1
:icons: font
:sectnums:
:sectnumlevels: 6
:sectnumoffset: A
:partnums:
:source-highlighter: rouge
:experimental:
:images-path: books/fdp-primer/

ifdef::env-beastie[]
ifdef::backend-html5[]
:imagesdir: ../../../../images/{images-path}
endif::[]
ifndef::book[]
include::shared/authors.adoc[]
include::shared/mirrors.adoc[]
include::shared/releases.adoc[]
include::shared/attributes/attributes-{{% lang %}}.adoc[]
include::shared/{{% lang %}}/teams.adoc[]
include::shared/{{% lang %}}/mailing-lists.adoc[]
include::shared/{{% lang %}}/urls.adoc[]
toc::[]
endif::[]
ifdef::backend-pdf,backend-epub3[]
include::../../../../../shared/asciidoctor.adoc[]
endif::[]
endif::[]

ifndef::env-beastie[]
toc::[]
include::../../../../../shared/asciidoctor.adoc[]
endif::[]

這些範例並非詳盡無遺 - 它們不包含所有可能需要使用的元素，尤其是在文件的卷首資料中。
有關 AsciiDoctor 的更多範例，請檢查 Git *doc* 儲存庫中可用的此文件和其他文件的 AsciiDoc 原始碼，或從 link:https://cgit.freebsd.org/doc/[https://cgit.freebsd.org/doc/] 線上取得。

[[examples-asciidoctor-book]]
== AsciiDoctor *book*

.AsciiDoctor *book*
[example]
====
[.programlisting]
....
---
title: 一本範例書
authors:
  - author: The FreeBSD Documentation Project
copyright: 1995-2021 The FreeBSD Documentation Project
releaseinfo: "" 
trademarks: ["general"] 
---

= 一本範例書
:doctype: book
:toc: macro
:toclevels: 2
:icons: font
:xrefstyle: basic
:relfileprefix: ../
:outfilesuffix:
:sectnums:
:sectnumlevels: 6
:partnums:
:chapter-signifier: 章
:part-signifier: 部分
:source-highlighter: rouge
:experimental:
:skip-front-matter:
:book: true
:pdf: false

ifeval::["{backend}" == "html5"]
:chapters-path: content/en/books/bookname/
endif::[]

ifeval::["{backend}" == "pdf"]
:chapters-path:
endif::[]

ifeval::["{backend}" == "epub3"]
:chapters-path:
endif::[]

[abstract]
摘要

摘要部分

'''

toc::[]

:sectnums!:

\include::{chapters-path}preface/_index.adoc[leveloffset=+1]

:sectnums:

\include::{chapters-path}parti.adoc[lines=7..18]

\include::{chapters-path}chapter-name/_index.adoc[leveloffset=+1]
....

====

[[examples-asciidoctor-article]]
== AsciiDoctor *article*

.AsciiDoctor *article*
[example]
====
[.programlisting]
....
---
title: 一篇範例文章
authors:
  - author: 您的姓名
    email: foo@example.com
trademarks: ["general"]
---

= 一篇範例文章
:doctype: article
:toc: macro
:toclevels: 1
:icons: font
:sectnums:
:sectnumlevels: 6
:source-highlighter: rouge
:experimental:

'''

toc::[]

== 我的第一節

這是我的文章的第一節。

=== 我的第一個子節

這是我的文章的第一個子節。

....

====
