---
title: 第 14 章. 商標
prev: books/fdp-primer/editor-config/
next: books/fdp-primer/see-also
description: FreeBSD 文件計畫中商標的指南
tags: ["trademarks", "AsciiDoctor", "HTML"]
showBookMenu: true
weight: 14
params:
  path: "/books/fdp-primer/trademarks/"
---

[[trademarks]]
= 商標
:doctype: book
:toc: macro
:toclevels: 1
:icons: font
:sectnums:
:sectnumlevels: 6
:sectnumoffset: 14
:partnums:
:source-highlighter: rouge
:experimental:
:images-path: books/fdp-primer/

ifdef::env-beastie[]
ifdef::backend-html5[]
:imagesdir: ../../../../images/{images-path}
endif::[]
ifndef::book[]
include::shared/authors.adoc[]
include::shared/mirrors.adoc[]
include::shared/releases.adoc[]
include::shared/attributes/attributes-{{% lang %}}.adoc[]
include::shared/{{% lang %}}/teams.adoc[]
include::shared/{{% lang %}}/mailing-lists.adoc[]
include::shared/{{% lang %}}/urls.adoc[]
toc::[]
endif::[]
ifdef::backend-pdf,backend-epub3[]
include::../../../../../shared/asciidoctor.adoc[]
endif::[]
endif::[]

ifndef::env-beastie[]
toc::[]
include::../../../../../shared/asciidoctor.adoc[]
endif::[]

對於 FreeBSD 文件計畫中的所有文件，引用註冊商標是必要的，引用其他商標是慣例，這是每位作者和貢獻者的要求。

[[trademark-symbols]]
== 商標符號

在商標名稱首次出現時，以及使用標誌時，請附加商標符號（(TM)、(R) 或其他）。
使用 extref:{fdp-primer}/writing-style/#writing-style-special-characters[對等的 ASCII 序列]，它將呈現為實際的 Unicode 字元。
此外，請遵循其商標指南撰寫商標名稱。

如有疑問，請研究商標所有者的網站、產品網站和/或 link:https://www.uspto.gov/trademarks[美國專利商標局商標搜尋網站]。

[[trademark-citing]]
== 商標引用

FreeBSD 文件計畫提供了一個引用商標的範本，這也避免了在文件中重複商標。

首先，在 link:https://cgit.freebsd.org/doc/tree/documentation/themes/beastie/i18n/en.toml#n328[專案範本的版權部分] 中尋找商標，然後將其新增到文件開頭的 `Front Matter` 部分的 trademarks 標籤中。

以下是 extref:{contributing}[貢獻 FreeBSD] 文章的 `Front Matter` 範例：

....
---
title: 貢獻 FreeBSD
authors:
  - author: Jordan Hubbard
  - author: Sam Lawrance
  - author: Mark Linimon
description: 如何貢獻 FreeBSD 專案
trademarks: ["freebsd", "ieee", "general"]
weight: 15
tags: ["Contributing", "FreeBSD", "Non-Programmer Tasks", "Programmer Tasks"]
---
....

商標標籤 `freebsd`、`ieee` 和 `general` 將在建置文件時自動呈現，如下所示：

....
FreeBSD 是 FreeBSD 基金會的註冊商標。

IEEE、POSIX 和 802 是電氣和電子工程師學會在美國的註冊商標。

製造商和銷售商用來區分其產品的許多名稱都被聲稱為商標。凡本文件中出現這些名稱，且 FreeBSD 專案知悉該商標聲明，則這些名稱後面均已加上「™」或「®」符號。
....

如果專案範本中沒有某個商標，則必須提交該商標。
任何開發人員或貢獻者都可以更新商標。

`freebsd` 和 `general` 商標標籤通常出現在所有文件中。
