---
title: 附录 A. 示例
prev: books/fdp-primer/see-also/
description: FreeBSD 文档项目中使用的文章和书籍示例
tags: ["examples", "tutorial", "AsciiDoctor", "Book", "Article"]
showBookMenu: true
weight: 16
params:
  path: "/books/fdp-primer/examples/"
---

[appendix]
[[examples]]
= 示例
:doctype: book
:toc: macro
:toclevels: 1
:icons: font
:sectnums:
:sectnumlevels: 6
:sectnumoffset: A
:partnums:
:source-highlighter: rouge
:experimental:
:images-path: books/fdp-primer/

ifdef::env-beastie[]
ifdef::backend-html5[]
:imagesdir: ../../../../images/{images-path}
endif::[]
ifndef::book[]
include::shared/authors.adoc[]
include::shared/mirrors.adoc[]
include::shared/releases.adoc[]
include::shared/attributes/attributes-{{% lang %}}.adoc[]
include::shared/{{% lang %}}/teams.adoc[]
include::shared/{{% lang %}}/mailing-lists.adoc[]
include::shared/{{% lang %}}/urls.adoc[]
toc::[]
endif::[]
ifdef::backend-pdf,backend-epub3[]
include::../../../../../shared/asciidoctor.adoc[]
endif::[]
endif::[]

ifndef::env-beastie[]
toc::[]
include::../../../../../shared/asciidoctor.adoc[]
endif::[]

这些示例并非详尽无遗——它们不包含所有可能希望使用的元素，尤其是在文档的前言部分。
有关 AsciiDoctor 的更多示例，请检查 Git *doc* 仓库中可用的此文档和其他文档的 AsciiDoc 源代码，或从 link:https://cgit.freebsd.org/doc/[https://cgit.freebsd.org/doc/] 开始在线查看。

[[examples-asciidoctor-book]]
== AsciiDoctor *book*

.AsciiDoctor *book*
[example]
====
[.programlisting]
....
---
title: 一本示例书籍
authors:
  - author: The FreeBSD Documentation Project
copyright: 1995-2021 The FreeBSD Documentation Project
releaseinfo: "" 
trademarks: ["general"] 
---

= 一本示例书籍
:doctype: book
:toc: macro
:toclevels: 2
:icons: font
:xrefstyle: basic
:relfileprefix: ../
:outfilesuffix:
:sectnums:
:sectnumlevels: 6
:partnums:
:chapter-signifier: Chapter
:part-signifier: Part
:source-highlighter: rouge
:experimental:
:skip-front-matter:
:book: true
:pdf: false

ifeval::["{backend}" == "html5"]
:chapters-path: content/en/books/bookname/
endif::[]

ifeval::["{backend}" == "pdf"]
:chapters-path:
endif::[]

ifeval::["{backend}" == "epub3"]
:chapters-path:
endif::[]

[abstract]
摘要

摘要部分

'''

toc::[]

:sectnums!:

\include::{chapters-path}preface/_index.adoc[leveloffset=+1]

:sectnums:

\include::{chapters-path}parti.adoc[lines=7..18]

\include::{chapters-path}chapter-name/_index.adoc[leveloffset=+1]
....

====

[[examples-asciidoctor-article]]
== AsciiDoctor *article*

.AsciiDoctor *article*
[example]
====
[.programlisting]
....
---
title: 一篇示例文章
authors:
  - author: 你的名字和姓氏
    email: foo@example.com
trademarks: ["general"]
---

= 一篇示例文章
:doctype: article
:toc: macro
:toclevels: 1
:icons: font
:sectnums:
:sectnumlevels: 6
:source-highlighter: rouge
:experimental:

'''

toc::[]

== 我的第一部分

这是我文章的第一部分。

=== 我的第一个小节

这是我文章的第一个小节。

....

====
