--- 
title: 第 9 章. PO 翻譯
prev: books/fdp-primer/translations
next: books/fdp-primer/weblate
description: 如何在 FreeBSD 文件計畫中使用 PO 翻譯
tags: ["po", "translations", "tutorial", "quick start"]
showBookMenu: true
weight: 9
params:
  path: "/books/fdp-primer/po-translations/"
---

[[po-translations]]
= PO 翻譯
:doctype: book
:toc: macro
:toclevels: 1
:icons: font
:sectnums:
:sectnumlevels: 6
:sectnumoffset: 9
:partnums:
:source-highlighter: rouge
:experimental:
:images-path: books/fdp-primer/

ifdef::env-beastie[]
ifdef::backend-html5[]
:imagesdir: ../../../../images/{images-path}
endif::[]
ifndef::book[]
include::shared/authors.adoc[]
include::shared/mirrors.adoc[]
include::shared/releases.adoc[]
include::shared/attributes/attributes-{{% lang %}}.adoc[]
include::shared/{{% lang %}}/teams.adoc[]
include::shared/{{% lang %}}/mailing-lists.adoc[]
include::shared/{{% lang %}}/urls.adoc[]
toc::[]
endif::[]
ifdef::backend-pdf,backend-epub3[]
include::../../../../../shared/asciidoctor.adoc[]
endif::[]
endif::[]

ifndef::env-beastie[]
toc::[]
include::../../../../../shared/asciidoctor.adoc[]
endif::[]

[[po-translations-introduction]]
== 簡介

http://www.gnu.org/software/gettext/[GNU gettext] 系統為翻譯人員提供了一種建立和維護文件翻譯的簡單方法。
可翻譯的字串會從原始文件中擷取到 PO (可攜式物件) 檔案中。
字串的翻譯版本會使用單獨的編輯器輸入。
這些字串可以直接使用，也可以建置成原始文件的完整翻譯版本。

[[po-translations-quick-start]]
== 快速入門

假設已執行 crossref:overview[overview-quick-start,快速入門] 中顯示的程序。
`TRANSLATOR` 選項是必要的，並且在 package:textproc/docproj[] port 中預設已啟用。

此範例顯示了簡短的 extref:{leap-seconds}[閏秒] 文章的西班牙文翻譯的建立過程。

[[po-translations-quick-start-install-po-editor]]

[.procedure]
====
.程序：安裝 PO 編輯器
. 需要 PO 編輯器來編輯翻譯檔案。此範例使用 package:editors/poedit[]。
+
[source,shell]
....
# pkg install poedit
....
====

[[po-translations-quick-start-initial-setup]]
[.procedure]
====
.程序：初始設定

首次建立新翻譯時，必須從英文原文建立或複製目錄結構：

. 為新翻譯建立目錄。英文文章原始碼位於 [.filename]#~/doc/documentation/content/en/articles/leap-seconds/#。西班牙文翻譯將位於 [.filename]#~/doc/documentation/content/es/articles/leap-seconds/#。路徑相同，但語言目錄名稱不同。
英文文章原始碼位於 [.filename]#~/doc/en/articles/leap-seconds/#。
西班牙文翻譯將位於 [.filename]#~/doc/es/articles/leap-seconds/#。
路徑相同，但語言目錄名稱不同。
+
[source,shell]
....
% mkdir ~/doc/documentation/content/es/articles/leap-seconds
....

. 將 [.filename]#_index.po# 從原始文件複製到翻譯目錄：
+
[source,shell]
....
% cp ~/doc/documentation/content/en/articles/leap-seconds/_index.po \
  ~/doc/documentation/content/es/articles/leap-seconds/
....

假設文件或語言也透過 Weblate 進行翻譯。
在這種情況下，最好從那裡取得 `.po` 檔案，並將翻譯文件上傳回平台，透過 Weblate 集中翻譯工作以避免重複工作。

請參閱 crossref:weblate[weblate-translating-offline,在 Weblate 上離線翻譯] 章節，了解如何下載 `.po` 檔案。
====

[[po-translations-quick-start-translation]]
[.procedure]
====
.程序：翻譯

使用 PO 編輯器在 PO 檔案中輸入翻譯。
有數種不同的編輯器可用。此處顯示的是 package:editors/poedit[] 中的 [.filename]#poedit#。

[source,shell]
....
% poedit documentation/content/es/articles/leap-seconds/_index.po
....
====

[[po-translations-quick-generating-a-translated-document]]
[.procedure]
====
.程序：產生翻譯後的文件
. 產生翻譯後的文件：
+
[source,shell]
....
% cd ~/doc
% ./tools/translate.sh documentation es articles/leap-seconds
....
+
產生的文件名與英文原文的名稱相符，通常是 [.filename]#_index.adoc#。
+
. 透過將產生的檔案轉譯為 HTML 並使用網頁瀏覽器檢視來檢查它：
+
[source,shell]
....
% cd ~/doc/documentation
% make
....
====

[[po-translations-creating]]
== 建立新翻譯

建立新翻譯文件的第一步是找到或建立一個目錄來存放它。
FreeBSD 將翻譯後的文件放在以其語言和地區命名的子目錄中，格式為 [.filename]#lang#。
_lang_ 是一個雙字元小寫代碼。

[[po-translations-language-names]]
.語言名稱
[cols="1,1,1", frame="none", options="header"]
|===
| 語言
| 地區
| 翻譯後目錄名稱

|英文
|美國
|[.filename]#en#

|孟加拉文
|孟加拉
|[.filename]#bn-bd#

|丹麥文
|丹麥
|[.filename]#da#

|德文
|德國
|[.filename]#de#

|希臘文
|希臘
|[.filename]#el#

|西班牙文
|西班牙
|[.filename]#es#

|法文
|法國
|[.filename]#fr#

|匈牙利文
|匈牙利
|[.filename]#hu#

|義大利文
|義大利
|[.filename]#it#

|日文
|日本
|[.filename]#ja#

|韓文
|韓國
|[.filename]#ko#

|蒙古文
|蒙古
|[.filename]#mn#

|荷蘭文
|荷蘭
|[.filename]#nl#

|波蘭文
|波蘭
|[.filename]#pl#

|葡萄牙文
|巴西
|[.filename]#pt-br#

|俄文
|俄羅斯
|[.filename]#ru#

|土耳其文
|土耳其
|[.filename]#tr#

|中文
|中國
|[.filename]#zh-cn#

|中文
|台灣
|[.filename]#zh-tw#
|===

翻譯位於主文件目錄的子目錄中，
此處假設為 [.filename]#~/doc/documentation/#，如 crossref:overview[overview-quick-start, 快速入門] 所示。
例如，德文翻譯位於 [.filename]#~/doc/documentation/content/de/#，
而法文翻譯位於 [.filename]#~/doc/documentation/content/fr/#。

每個語言目錄都包含以文件類型命名的單獨子目錄，通常是 [.filename]#articles/# 和 [.filename]#books/#。

結合這些目錄名稱即可得到文章或書籍的完整路徑。
例如，NanoBSD 文章的法文翻譯位於 [.filename]#~/doc/documentation/content/fr/articles/nanobsd/#，
而手冊的蒙古文翻譯位於 [.filename]#~/doc/documentation/content/mn/books/handbook/#。

將文件翻譯成新語言時，必須建立新的語言目錄。
如果語言目錄已存在，則只需要在 [.filename]#articles/# 或 [.filename]#books/# 目錄中建立一個子目錄。

[[po-translations-creating-example]]
.建立 Porter 手冊的西班牙文翻譯
[example]
====
建立 extref:{porters-handbook}[Porter 手冊] 的新西班牙文翻譯。
原文是一本書，位於 [.filename]#~/doc/documentation/content/en/books/porters-handbook/#。

[.procedure]
======

. 西班牙文語言書籍目錄 [.filename]#~/doc/documentation/content/es/books/# 已存在，因此只需要為 Porter 手冊建立一個新的子目錄：
+
[source,shell]
....
% cd ~/doc/documentation/content/es/books
% mkdir porters-handbook
....

. 從原始書籍複製內容：
+
[source,shell]
....
% cd porters-handbook
% cp -R ~/doc/documentation/content/en/books/porters-handbook/* .
....
+ 現在文件結構已準備好，翻譯人員可以使用 `po4a` 指令開始翻譯。
======
====

[[po-translations-translating]]
== 翻譯

gettext 系統大大減少了翻譯人員必須追蹤的事項。
要翻譯的字串會從原始文件中擷取到 PO 檔案中。
然後使用 PO 編輯器輸入每個字串的翻譯版本。

FreeBSD PO 翻譯系統不會覆寫 PO 檔案，因此可以隨時執行擷取步驟來更新 PO 檔案。

PO 編輯器用於編輯檔案。
此範例中顯示了 package:editors/poedit[]，因為它簡單且要求最低。
其他 PO 編輯器提供了一些功能，可以讓翻譯工作變得更容易。
Ports Collection 提供了其中幾種編輯器，包括 package:devel/gtranslator[]。

保留 PO 檔案非常重要。
它包含了翻譯人員所做的所有工作。

[IMPORTANT]
====
在 FreeBSD 上，線上翻譯文件證明是文件翻譯最簡單的方法，因為它允許多個使用者協作同一個檔案，有效地分配工作量。
有關更多詳細資訊，請參閱下一章 crossref:weblate[weblate-introduction,Weblate 翻譯]。
====

[[po-translations-tips]]
== 翻譯人員提示

[[po-translations-tips-xmltags]]
=== 保留 AsciiDoc 巨集

保留英文原文中顯示的 AsciiDoc 巨集。

.保留 AsciiDoc 巨集
[example]
====
英文原文：

[.programlisting]
....
msgid ""
"This example shows the creation of a Spanish translation of the short "
"extref:{leap-seconds}[Leap Seconds] article."
....

西班牙文翻譯：

[.programlisting]
....
msgid ""
"Este ejemplo muestra la creación de un artículo con poco contenido como el artículo "
"extref:{leap-seconds}[Leap Seconds]."
....

====

[[po-translations-tips-spaces]]
=== 保留空格

保留要翻譯的字串開頭和結尾的現有空格。
翻譯後的版本也必須有這些空格。

[[po-translations-tips-verbatim]]
=== 逐字標籤

某些標籤的內容應逐字複製，而不是翻譯：

* `man:man[1]`
* `package:package[]`
* `link`
* `image`
* `include`
* `Admonitions`
* `id's`
* `Heading tags`
* `source`

[[po-translations-building]]
== 建置翻譯後的文件

可以隨時建立原始文件的翻譯版本。
原始文件中任何未翻譯的部分都將以英文包含在產生的文件中。
大多數 PO 編輯器都有一個指標，顯示翻譯完成的程度。
這讓翻譯人員可以輕鬆地看到何時已翻譯足夠的字串，值得建置最終文件。

Weblate 章節提供了一個完整的範例，說明如何 crossref:weblate[weblate-building,建置翻譯後的文件]。

[[po-translations-submitting]]
== 提交新翻譯

準備好要提交的新翻譯檔案。
這包括將檔案新增到版本控制系統、設定其其他屬性，然後建立一個用於提交的 diff。

這些範例建立的 diff 檔案可以附加到 https://bugs.freebsd.org/bugzilla/enter_bug.cgi?product=Documentation[文件錯誤報告] 或 https://reviews.freebsd.org/[程式碼審查]。

[[po-translations-submitting-spanish]]
.NanoBSD 文章的西班牙文翻譯
[example]
====
[.procedure]
======

. 從 [.filename]#~/doc/# 基礎目錄建立新檔案的 diff，以便檔名顯示完整路徑。這有助於提交者識別目標語言目錄。
+
[source,shell]
....
% cd ~/doc
% git diff documentation/content/es/articles/nanobsd/ > /tmp/es_nanobsd.diff
....
======

Weblate 章節提供了一個完整的範例，說明如何 crossref:weblate[weblate-submitting-translations,提交新翻譯]。

===
